name: tms_app_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+43
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.4
  double_back_to_close: ^2.0.0
  new_gradient_app_bar: ^0.2.0
  flutter_barcode_scanner: ^2.0.0
  geolocator: ^7.0.0
  syncfusion_flutter_datepicker: ^19.4.41
  shared_preferences: ^2.0.12
  nb_utils: ^4.4.10
  dots_indicator: ^2.0.0
  flutter_svg: ^0.23.0+1
  cached_network_image: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_cupertino_settings: ^0.5.0
  extended_masked_text: ^2.3.1
  flutter_multi_formatter: ^2.5.1
  flutter_material_pickers: ^3.1.2
  pattern_formatter: ^2.0.0
  url_launcher: ^6.0.18
  status_change: ^2.0.0
  skeletons: ^0.0.3
  flutter_local_notifications: ^9.3.2
  flutter_background_service: ^0.2.5
  device_info_plus: ^3.2.2
  get_storage: ^2.0.3
  clipboard: ^0.1.3
  ota_update: ^4.0.1
  percent_indicator: ^4.0.0
  accordion: ^2.2.3
  expandable: ^5.0.1
  step_progress_indicator: ^1.0.2
  pull_to_refresh: ^2.0.0
  easy_localization: ^3.0.0

  



dev_dependencies:
  flutter_test:
    sdk: flutter

  
flutter:
  uses-material-design: true
  assets:
    - assets/menu_icon/
    - assets/trip_img/
    - assets/gif/
    - assets/success/
    - assets/menu_image/
    - assets/template/quiz/
    - assets/translations/
  #   - images/a_dot_ham.jpeg

